### ISSUE TITLE
where do yo find the package seacore and seaware that are required by e3fp?

### ISSUE THREAD

**Issue by zzLan** [keiserlab/e3fp-paper#1]
runfile('/Users/zlan/Documents/source/e3fp-paper/project/scripts/generate_e3fp_fprints.py', wdir='/Users/zlan/Documents/source/e3fp-paper/project/scripts')

ModuleNotFoundError: No module named 'seacore'

**Comment by sethaxen** [comment]
As noted in the README, use of the scripts in this repo requires an installation of the SeaWare package. This package includes `seaware`, `seacore`, `fpcore`, and `seashell`. [E3FP](https://github.com/keiserlab/e3fp) itself is independent of SEA and does not require these packages. To obtain a copy of SeaWare, you'll need to contact [SeaChange Pharmaceuticals](https://www.seachangepharma.com/store/academic/products) for a license.

**Comment by tbwxmu** [comment]
Is there any other free SEA package here?

**Comment by mjke** [comment]
@tbwxmu - No, as mentioned previously, SEAware source code is a commercial package. E3FP does not require SEAware or its packages.
